# Generated by Django 3.2.5 on 2021-07-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroNota', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
