# Generated by Django 3.2.5 on 2021-07-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
        ('maestro', '0001_initial'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('maestro', models.ManyToManyField(to='maestro.maestro')),
                ('materias', models.ManyToManyField(to='materias.materias')),
                ('notas', models.ManyToManyField(to='notas.notas')),
            ],
        ),
    ]
